app = "xfbraid"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
auto_rollback = true

[build]
dockerfile = "Dockerfile.production"

[env]
SERVER_ADDR = "0.0.0.0:3000"
RUST_LOG = "info,backend=info"
LEPTOS_SITE_ROOT = "site"
LEPTOS_SITE_ADDR = "0.0.0.0:3000"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[http_service.checks]]
grace_period = "15s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/api/health"

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1

[deploy]
strategy = "rolling"
